In [1]:
from Regression.data_management import *
import numpy as np
import matplotlib.pyplot as plt
import tflearn

# save_data('./DATA/BDD1_traite/', './DATA/BDD1_BB.txt', 'Regression/BDD1.npz')
data = load_data('BDD1.npz')

In [2]:
Y = data.Train.Label
X = data.Train.Images
np.shape(X)
print(Y[0,:])
print(X[6,:])

[ 98 110 161 225]
[-3.93366814 -3.01013184 -3.53346896 ...,  1.26891863 -1.07070613
  0.71479702]


In [16]:
V,W=tflearn.data_utils.shuffle(X,Y)
np.shape(V)
print(W[0,:])

[104 121  17  55]


In [23]:
X-=np.mean(X)
X /= np.std(X)
X

array([[-0.21076626,  0.1456581 ,  0.81854953, ...,  0.79292033,
         0.59591102, -1.61615308],
       [ 0.92796265, -0.2852123 ,  1.03398473, ...,  0.17739119,
         0.01115834,  0.13810498],
       [ 1.66659762,  1.68448095, -1.70511995, ...,  0.70059096,
         1.24221662, -0.29276542],
       ..., 
       [-3.07297677, -3.5167403 , -0.07396773, ...,  0.97757907,
        -0.94291183, -0.90829456],
       [ 0.15855123, -0.10055356, -0.78182624, ..., -0.13037338,
        -0.819806  ,  0.44586955],
       [ 1.60504471,  1.16128118,  1.18786701, ...,  0.79292033,
         0.34969937,  0.69208121]])